bcgov/citz-imb-salary-estimate-tool

.github/CODEOWNERS

[SET-131](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-131)
- Adds CODEOWNERS file

SET-131: Add CODEOWNERS file.

---

api/.docker/Dockerfile.dev
docker-compose.dev.yaml
frontend/.docker/Dockerfile.dev

[SET-132](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-132)
- Adds Dockerfiles
- Adds docker-compose

SET-132: Add Dockerfiles & docker-compose.

---

api/package.json
docker-compose.dev.yaml

- Fix db volume mounting
- Add nodemon
- Add 'dev' npm script

SET-133: Docker working now.

---

frontend/vite.config.ts

- Added server objects in vite.config

[SET-129] Frontend docker fix

---

.github/helpers/deploy.sh
.github/labeler.yaml
.github/workflows/api-build-deploy.yaml
.github/workflows/pr-image-build-api.yaml
.github/workflows/pr-image-build-app.yaml
.github/workflows/pr-labeller.yaml

- Adds GitHub Action workflow files
- Adds deploy.sh

Add workflow files & deploy.sh

---

.github/workflows/api-build-deploy.yaml
.github/workflows/pr-image-build-api.yaml
.github/workflows/pr-image-build-app.yaml

- Amends workflows to specify using docker-compose.dev.yaml

SET-134: Amend workflows

---

.github/workflows/api-build-deploy.yaml
.github/workflows/pr-image-build-api.yaml
.github/workflows/pr-labeller.yaml
docker-compose.dev.yaml

- Change .env creation path and associated value echoes

SET-134: Fix missing .env on build.

---

.github/workflows/pr-labeller.yaml

- Fix labeller config file path

SET-134: Fix labeller config file path.

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md

[SET-136](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-136)
- Add PR template and Code of Conduct

SET-136: Pull Request Template

---

.github/auto-assign-config.yaml
.github/workflows/pr-auto-assign.yaml

[SET-137](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-137)
- Auto assign author to PR as assignee

SET-137: Add auto assign for PR author

---

docker-compose.dev.yaml
frontend/src/App.tsx

SET-134: Remove db env file path quotations

---

.github/workflows/pr-image-build-app.yaml

- Creates empty .env in the api dir for the frontend pr image build workflow

SET-134: Create an api/.env file in the frontend workflow.

---

docker-compose.dev.yaml

SET-134: Remove env file spec from api compose.

---

README.md

[SET-141](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-141)
- Change README header
- Add product lifecycle badge — Resolves: #5 

SET-141: Product Lifecycle Badge

---

.github/workflows/pr-image-build-app.yaml

- Provides a brief explanation of the .env creation during the FE image build workflow

SET-134: Comment for .env creation for FE image build.

---

.github/workflows/api-build-deploy.yaml
.github/workflows/app-build-deploy.yaml

- Adds the deployment workflow for the frontend
- Fixes the incorrect naming of the namespace parameter for the openshift login step in both the api and frontend deployment workflows

SET-134: Deploy workflow for deploying the frontend.

---

docker-compose.dev.yaml

- Adds env_file to api image due to deploy error specified during action run

SET-134: Add env_file spec to api compose

---

.github/workflows/api-build-deploy.yaml
docker-compose.dev.yaml

SET-134: Add manual .env creation to deployment workflow

---

.github/workflows/api-build-deploy.yaml
.github/workflows/app-build-deploy.yaml

SET-134: Fix docker push & tag urls for FE & API build-deploys.

---

openshift/set-api-dc-template.yaml
openshift/set-app-dc-template.yaml

- Creates FE and API deployment configs

SET-143: DeploymentConfigs

---

.github/workflows/api-build-deploy.yaml
.github/workflows/app-build-deploy.yaml

- docker ls => docker image ls

SET-143: Deployment configs

---

.github/workflows/api-build-deploy.yaml
.github/workflows/app-build-deploy.yaml

SET-143: Correct the image tag names.

---

.github/workflows/api-build-deploy.yaml

- Gut check on pushing to oc image repo

SET-143: Gut check

---

.github/helpers/deploy.sh

SET-143: Fix casing for deploy.sh

---

.github/helpers/deploy.sh

SET-143: Remove unknown parameter from deploy script

---

.github/helpers/deploy.sh
.github/workflows/api-build-deploy.yaml

- Change deploy.sh to run `oc process` from the tools namespace and deploy *to* the dev namespace

SET-143: Change namespace for template.

---

.github/helpers/deploy.sh
.github/workflows/api-build-deploy.yaml

SET-143: Hard code deploy params to check correctness.

---

.github/helpers/deploy.sh
.github/workflows/api-build-deploy.yaml
openshift/templates/set-api-dc-template.yaml

SET-143: Gut check for deploy values.

---

.github/helpers/deploy.sh

- Gut check for deploy values.
- Deploy.sh OPENSHIFT_NAMESPACE hard code value.
- See title
Conduct](/CODE_OF_CONDUCT.md) document.

SET-143: Hard-code deploy namespace value

---

.github/workflows/api-build-deploy.yaml

SET-143: Pass in correct SA token for deploy script.

---

openshift/templates/set-api-dc-template.yaml

SET-143: Hard-code img repo for api dc template spec.

---

api/.docker/Dockerfile.dev

SET-143: Change API container npm cache dir

---

api/.docker/Dockerfile.dev

- Force npm cache clean in API container

SET-143: Force API container npm cache clean.

---

.github/workflows/api-build-deploy.yaml
api/.docker/Dockerfile.prod
docker-compose.prod.yaml

- See title
- Creates API Dockerfile.prod
- Adds docker-compose.prod.yaml

SET-143: Push a built API image instead of development image.

---

api/.docker/Dockerfile.prod

SET-143: Change API base image.

---

api/.docker/Dockerfile.prod

SET-143: Remove API /docs copy

---

.github/workflows/pr-image-build-api.yaml

SET-143: PR build prod API image.

---

api/middleware/globalErrorHandler.ts

-Added to globalErrorHandler comment to test the Api  build-deploy (will remove)

[SET-143] test api build-deploy

---

api/middleware/globalErrorHandler.ts

- Removed Comment for testing workflow

[SET-143] Testing Workflow

---

api/.docker/Dockerfile.prod
api/middleware/globalErrorHandler.ts

- Added comment for workflow test
- Added new user to dockerfile.prod in api

[SET-143] Added comment for test

---

api/.docker/Dockerfile.prod

- Removed new user from dockerfile
[SET-143](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?seletedIssue=DEVOP-143)

[SET-143] Dockerfile update

---

openshift/templates/set-api-dc-template.yaml

[SET-160](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-160)
- See title

SET-160: Change API dc container port

---

api/middleware/globalErrorHandler.ts

- Removed a comment in the api to test the workflow
[SET-160](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-160)

[SET-160] Test API workflow

---

api/express.ts
api/server.ts

- Removed all non essentials from express.ts and added a console.log for errors in server.ts
[SET-145](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssues=DEVOP-145)

[Set-145] API Test

---

api/server.ts

- Eslint console.log rule disabled
[SET-145](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-145)

[SET-145]- Eslint rule disabled

---

api/express.ts
api/server.ts

- Added the health endpoint back to test in openshift
[SET-145](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssues=DEVOP-145)

[SET-145] API Health endpoint

---

.github/workflows/app-build-deploy.yaml
docker-compose.prod.yaml
frontend/.docker/Dockerfile.prod
frontend/nginx.conf
openshift/templates/set-app-dc-template.yaml

[SET-161](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-161)
- See title

SET-161: Frontend Deployment

---

.github/workflows/app-build-deploy.yaml

[SET-161](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-161)
- See title

SET-161: Fix deploy workflow token name

---

openshift/templates/set-app-dc-template.yaml

[SET-161](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-161)
- See title

SET-161: Fix app dc template image repo

---

openshift/templates/set-api-dc-template.yaml

[SET-164](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-164)
- See title

SET-164: Fix API DC

---

openshift/templates/set-api-dc-template.yaml

[SET-164](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-164)
- See title

SET-164: Fix formatting

---

openshift/templates/set-api-dc-template.yaml

[SET-164](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-164)
- See title

SET-164: Fix formatting, Act 2

---

.github/helpers/deploy.sh

[SET-166](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-166)
- See title

SET-166: Remove deploy script variables

---

.github/helpers/deploy.sh

[SET-166](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-166)
- See title

SET-166: Add '|' to deploy.sh command

---

openshift/templates/set-app-dc-template.yaml

[SET-165](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-165)
- See title

SET-165: Fix Frontend DC

---

frontend/nginx.conf

[SET-165](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=SET-165)
- See title

SET-165: Fix nginx.conf

---

openshift/templates/set-api-svc-template.yaml

[SET-175](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-175)
- See title

SET-175: API Service Template

---

openshift/templates/set-app-svc-template.yaml

[SET-174](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-174)
- See title

SET-174: Frontend Service Template

---

openshift/templates/set-api-rt-template.yaml

[SET-177](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-177)
- See title

SET-177: API Route Template

---

openshift/templates/set-app-rt-template.yaml

[SET-178](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-178)
- See title

SET-178: Frontend Route Template

---

.github/workflows/api-build-deploy.yaml

[SET-189](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-189)
- See title

SET-189: API Build Deploy

---

.github/workflows/app-build-deploy.yaml

[SET-190](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-190)
- See title

SET-190: Frontend Build Deploy

---

.github/workflows/api-build-deploy.yaml

[SET-191](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-191)
- See title

SET-191: Add DATABASE_URL Env. Variable

---

api/.docker/Dockerfile.prod
api/prisma/seed.ts

[SET-193](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-193)
- Uncomment code in seed.ts for Dallas
- Force clean npm cache

SET-193: Fix API npm perms

---

api/.docker/Dockerfile.prod

[SET-193](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-193)
- See title

SET-193: Move 'npm cache clean' to earlier in the image build process

---

api/.docker/Dockerfile.prod

[SET-193](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-193)
- See title

SET-193: Fix .npm dir perms

---

api/.docker/Dockerfile.prod

[SET-192] Updated dockerfile

---

api/.docker/Dockerfile.prod

[SET-192] Prisma Fix

---

api/.docker/Dockerfile.prod

Added COPY of prisma to prod

---

api/.docker/Dockerfile.prod
api/startProd.sh

[SET-192] Added directory lists

---

api/startProd.sh

[SET-192] Removed comments from startProd

---

api/startProd.sh

[SET-192] .sh issue fix

---

api/.docker/Dockerfile.prod
api/startProd.sh

[SET-192] Updated dockerfile.prod

---

api/.docker/Dockerfile.prod
api/startProd.sh

[SET-192] Updated CMD in dockerfile

---

api/.docker/Dockerfile.prod

[SET-192] Added chmod rules to startProd.sh

---

api/.docker/Dockerfile.prod
api/startProd.sh

See title
[SET-192](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18/selectedIssues=DEVOP-192)

[SET-192] Fixed issue in startProd.sh and updated dockerfile

---

api/startProd.sh

[SET-192] Changed to npm run start

---

openshift/templates/set-api-dc-template.yaml

[SET-194](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-194)
- See title

SET-194: Add env spec to API dc template

---

api/.docker/Dockerfile.prod
frontend/.docker/Dockerfile.prod
openshift/templates/set-app-dc-template.yaml

[SET-195](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-195)
- See title
- Frontend Dockerfile.prod now exposes port 8080

SET-195: Fix app dc container port

---

api/startDev.sh

[SET-192] Removed call to seed for now

---

api/startDev.sh
api/startProd.sh

[SET-192] Commented out seed command for now

---

.github/helpers/test-config.yaml
.github/workflows/pr-api-unit-tests.yaml

[SET-197](https://citz-imb.atlassian.net/jira/software/c/projects/DEVOP/boards/18?selectedIssue=DEVOP-197)
- API Unit Tests Workflow
- helpers/test-config.yaml

SET-197: API Units Tests Workflow

---

.github/workflows/api-build-deploy.yaml

SET-199: Add registry-user & registry-password inputs to Docker Scout

---

.github/workflows/api-build-deploy.yaml

SET-199: Use docker-username & docker-password for Docker Scout

---

.github/workflows/api-build-deploy.yaml

SET-199: Try supplying GITHUB_TOKEN to Docker scout

---

.github/workflows/api-build-deploy.yaml

SET-199: Provide Docker Hub creds for Scout usage

---

.github/workflows/api-build-deploy.yaml

SET-199: Fix docker creds key typos

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/app-build-deploy.yaml

[SET-16](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-16)
- See title

SET-16: Add Docker Scout to app-build-deploy

---

.github/workflows/api-build-deploy.yaml
.github/workflows/app-build-deploy.yaml

[SET-22](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-22)
- See title

SET-22: Docker Scout only on PR

---

.github/CODEOWNERS

[SET-29](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-29)
- See title

SET-29: Add Scott to CODEOWNERS

---

api/prisma/schema.prisma

- Added new target to binary tragets in schema.prisma
[SET-30](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-30)

[SET-30] Prisma Windows Dev

---

.github/workflows/api-build-deploy.yaml

- SET-32: Update API env mapping in deploy workflow
- SET-32: Add env PORT==API_PORT mapping
[SET-32](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-32)
- See title

SET-32: Update API env mapping in deploy workflow

---

frontend/nginx.conf

- Removed service name from nginx.config
[SET-33](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-33)

[SET-33] Openshiftfix

---

openshift/templates/set-app-rt-template.yaml

[SET-34](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-34)
- See title

SET-34: Alter Frontend Route Template

---

api/express.ts

- Disabled cors for testing
[SET-33](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-33)

[SET-33] Cors Disabled

---

frontend/index.html

[SET-35](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-35)

SET-35 fixed margin

---

.github/workflows/api-build-deploy.yaml
.github/workflows/pr-image-build-api.yaml
api/.docker/Dockerfile.prod
api/express.ts
api/package.json
docker-compose.prod.yaml
frontend/nginx.conf

- Fixed issue with proxy passing and nginx
[SET-33](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-33)

[SET-33] Nginx Fix

---

.github/workflows/api-build-deploy.yaml

[SET-39](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-39)
- See title

SET-39: Fix API build-deploy workflow

---

openshift/templates/set-api-dc-template.yaml

[SET-40](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-40)
- See title

SET-40: Update API DeploymentConfig Template

---

openshift/templates/set-api-dc-template.yaml

[SET-40](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-40)
- See title

SET-40: Update API DC Template secret mapping.

---

.github/workflows/api-build-deploy.yaml
.github/workflows/app-build-deploy.yaml
.github/workflows/pr-image-build-api.yaml
.github/workflows/pr-image-build-app.yaml

[SET-42](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-42)
- See title

SET-42: Refactor Docker Scout Implementation

---

api/prisma/migrations/20231030154350_fourth/migration.sql
api/prisma/migrations/20231030160418_/migration.sql
api/prisma/schema.prisma

- Updated the user model to include more user info
- Made another migration to account for the schema changes
[SET-31](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-31)

[SET-31] User Model Update

---

api/controllers/inquiry-controller.ts
api/controllers/user-controller.ts
api/express.ts
api/prisma/data.mjs
api/prisma/seed.mjs
api/routes/inquiry-router.ts

- Added inquiry/guid that returns all inquiries related to that user
- Added, create, update, and delete operations to the inquiry
- Updated seed data for dev
[SET-44](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-44)

[SET-44] Inquiry CRUD Operations

---

api/controllers/inquiry-controller.ts
api/docs/routeDocs/inquiry.yaml
api/routes/inquiry-router.ts

- Added a new function in the controller to return an inquiry by it's id
- Updated swagger docs
[SET-50](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-50)

[SET-50] Added GET to the inquiry/:id route

---

.github/CODEOWNERS

- Added other devs as code owners to provide feedback
[SET-52](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-52)

[SET-52] Add Code Owners

---

.github/CODEOWNERS
.github/auto-assign-config.yaml

[SET-53](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-53)
- See title
- Remove non-contributing reviewers from CODEOWNERS

SET-53: Auto-assign non-contributing reviewers

---

api/config/keycloakConfig.ts
api/controllers/user-controller.ts
api/express.ts
api/package.json
api/utils/activateUser.ts
frontend/package.json
frontend/src/main.tsx
frontend/src/pages/Home.tsx

- Updated Keycloak packages in frontend and api package.json
- Updated imports in necessary files
[SET-51](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-51)

[SET-51] Updated Keycloak Packages

---

frontend/src/App.tsx
frontend/src/components/Navbar/Navbar.test.tsx
frontend/src/components/Navbar/Navbar.tsx
frontend/src/components/buttons/AuthenticationButton.tsx
frontend/src/pages/Home.test.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Inquiry.test.tsx
frontend/src/pages/Inquiry.tsx

[SET-55](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-55)
This PR also resolves a login issue discovered in PR #162 and should be committed after that PR is committed
converted to draft

Set 55 - Add Login button to navbar

---

api/controllers/admin-data-controller.ts
api/express.ts
api/routes/admin-data-router.ts
api/routes/index.ts

- Added Admin Data controller and get methods for the ministry, Experience, Process, and appointment tables
- Add router for admin data
[SET-70](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-70)

[SET-70] Admin Data Endpoint

---

api/prisma/data.mjs
api/prisma/migrations/20231211222502_/migration.sql
api/prisma/schema.prisma

- See title
[SET-77](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-77)

[SET-77] Added definition to salary ranges

---

frontend/src/components/buttons/ConfirmCancelButton/ConfirmCancelButton.tsx
frontend/src/components/buttons/DeleteRowButton/DeleteRowButton.tsx
frontend/src/components/buttons/index.ts
frontend/src/components/dialogs/DeleteConfirmationDialog/DeleteConfirmationDialog.tsx
frontend/src/components/dialogs/index.ts
frontend/src/components/forms/form.d.ts
frontend/src/components/table/InquiryTableContainer/InquiryTableContainer.tsx
frontend/src/components/table/TableContainer/TableContainer.tsx
frontend/src/hooks/useAPI/useAPI.ts
frontend/src/hooks/useDataFactory/useData.Factory.ts
frontend/src/hooks/useFormFactory/useForm.Factory.tsx
frontend/src/hooks/useInquiry/useInquiry.ts

[SET-62](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-62)

Set-62-Add-Delete-Record-for-Inquiries

---

frontend/src/components/fields/CurrencyField/CurrencyField.tsx
frontend/src/components/fields/MultilineField/MultilineField.tsx
frontend/src/components/fields/NumberField/NumberField.tsx
frontend/src/components/fields/SelectField/SelectField.tsx
frontend/src/components/fields/TextField/TextField.tsx
frontend/src/hooks/useDataFactory/useData.Factory.ts

[SET-81](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-81)

Set-81-fix-update-linting-error

---

.gitattributes
package.json

- Before if package-lock file didn't exist the command would error.
- Added git attributes so files uploaded to repo use LF as EOL.

Fix install scripts

---

.github/CODEOWNERS

- Updated code owners file to include other devs
[SET-93](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-93)

[SET-93] Update CodeOwners

---

api/controllers/ministry-controller.ts
api/docs/routeDocs/ministry.yaml
api/docs/schemaDocs/Ministry.yaml
api/express.ts
api/prisma/data.mjs
api/prisma/migrations/20240110234936_/migration.sql
api/prisma/schema.prisma
api/prisma/seed.mjs
api/routes/index.ts
api/routes/ministry-router.ts
api/tests/integration/api-ministry-data.test.js
frontend/src/hooks/index.ts
frontend/src/hooks/useMinistry/ministry.columns.tsx
frontend/src/hooks/useMinistry/ministry.fields.tsx
frontend/src/hooks/useMinistry/ministry.sections.tsx
frontend/src/hooks/useMinistry/useMinistry.ts
frontend/src/pages/Home/Home.tsx
frontend/src/types/Ministry.d.ts
frontend/src/types/index.ts

- Added ministry columns, and types on frontend.
- Added a ministry hook on the homepage.
- Added router and controller functions to enable CRUD functionality on the backend.
- Updated 'Ministry' schema, changing the primary key data type of the id field from string to integer to ensure better data consistency.
- Added integration test and swagger docs.
[SET-80](https://citz-imb.atlassian.net/browse/SET-80?atlOrigin=eyJpIjoiODc4NDBkMDU5MTM1NDJhNzgzZDg3MmZkOTdlMGQxODYiLCJwIjoiaiJ9)
> - I have consulted with the team if introducing a new …

[SET-80] Add Ministry Tab to home page

---

frontend/src/hooks/index.ts
frontend/src/hooks/useExperience/experience.columns.tsx
frontend/src/hooks/useExperience/experience.fields.tsx
frontend/src/hooks/useExperience/experience.sections.tsx
frontend/src/hooks/useExperience/useExperience.ts
frontend/src/pages/Home/Home.tsx
frontend/src/types/Experience.d.ts
frontend/src/types/index.ts

[SET-83](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-83)
- create experience types
- create experience hook
- add experience tab to home page]

SET-83: add experience tab to home page

---

.github/workflows/pr-image-build-api.yaml
.github/workflows/pr-image-build-app.yaml
api/.docker/Dockerfile.dev
api/.docker/Dockerfile.prod
docker-compose.dev.yaml
docker-compose.prod.yaml
frontend/.docker/Dockerfile.dev
frontend/.docker/Dockerfile.prod

[SET-47](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-47)
- Refactored PR image build workflows to accept a repo configurable BASE_IMAGE_TAG variable
- Updated Docker artifacts to use the new BASE_IMAGE_TAG variable and provided a, currently, stable default value

SET-47: Update image to remove vulnerabilities

---

.github/helpers/test-config.yaml
.github/workflows/pr-api-unit-tests.yaml

[SET-97](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-97)
- Refactors 'pr-api-unit-tests.yaml' to remove deprecated syntax
- Updates the 'test-config.yaml' to use current integration test naming convention

SET-97: Update API Unit Test Workflow

---

.github/config/dep-report.json5
.github/helpers/create-npm-dep-report-issues.js
.github/helpers/create-npm-dep-report.js
.github/helpers/github-api/create-and-close-existing-issue.js
.github/helpers/github-api/github-api-requests.js
.github/helpers/parse-json5-config.js
.github/helpers/parse-npm-deps.js
.github/workflows/npm-dep-report.yaml

[SET-99](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-99)
Adds new workflow for checking npm dep versions.

Added npm dep workflow and supporting files

---

.github/helpers/create-npm-dep-report.js

[SET-100](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-100)
- Doesn't affect this project but wanted to keep the file up-to-date.
- Makes the report not show the part to change directory if the package path is root directory.

Updated NPM Dep Report

---

.github/config/dep-report.json5
.github/helpers/create-npm-dep-report.js
.github/helpers/parse-npm-deps.js
.github/labeler.yaml
.github/workflows/e2e-test.yaml

[SET-98](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-98)
- create e2e test workflow
- update npm dependency workflows to include e2e folder

SET 98: create e2e test Github actions workflow

---

.github/helpers/create-npm-dep-report.js
.github/helpers/parse-npm-deps.js
.github/workflows/e2e-test.yaml

[SET-98](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-98)
- update e2e folder paths
- update npm dependency folder paths

SET-98: create e2e test Github actions workflow

---

.github/workflows/pr-api-unit-tests.yaml

[SET-105](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-105)
- Fixes ids in the api unit tests workflow

SET-105: Fix API unit tests workflow

---

.github/workflows/pr-api-unit-tests.yaml

[SET-106](https://citz-imb.atlassian.net/jira/software/c/projects/SET/boards/51?selectedIssue=SET-106)
- Remove `-e` flag from `yq` command in api unit test workflow

SET-106: API Test Workflow yq
